server.port=8081
jdbc.driver=org.sqlite.JDBC
jdbc.url=jdbc:sqlite:/Users/ioan/Desktop/Concurs.db
jdbc.user=username
jdbc.pass=password
# JWT Configuration
jwt.secret=123456789123456789123456789123456789
jwt.expiration=86400  